variables:
  DOCKER_IMAGE_TAG: $CI_PIPELINE_IID
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG

stages:
  - build
  - release

build:image:dev:
  stage: build
  tags:
    - shell-build-runer
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    LINUX_AMD_LINK: "https://git.pepemoss.com/api/v4/projects/${CI_PROJECT_ID}/packages/generic/release/$CI_COMMIT_TAG/picker-linux-amd64"
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker create --name temp_container $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker cp temp_container:/output .
    - docker rm temp_container
    - echo $LINUX_AMD_LINK
    - curl --header "PRIVATE-TOKEN: $CI_ACCESS_TOKEN" --upload-file ./output/picker-linux-amd64 "$LINUX_AMD_LINK"
    - curl --request POST "https://git.pepemoss.com/api/v4/projects/${CI_PROJECT_ID}/releases" \
          --header "PRIVATE-TOKEN: $CI_ACCESS_TOKEN" \
          --data "name=Release Tag - $CI_COMMIT_TAG" \
          --data "tag_name=$CI_COMMIT_TAG" \
          --data "description=All Release builds for Tag - $CI_COMMIT_TAG" \
          --data-urlencode "assets[links][][name]=Linux-Amd64-$CI_COMMIT_TAG" \
          --data-urlencode "assets[links][][url]=$LINUX_AMD_LINK"
