[general]
name = "Hotkey Bublik"
description = "Управляет командами, отправляемыми в `Input` `UnitNodes` других `Unit`. Позволяет вызывать команду выбором сегмента  и/или назначать для команд горячие клавиши"
language = "Golang"
hardware = ["Any-PC"]
firmware = ["Linux", "X11", "I3WM"]
stack = [
    {name = "ebiten-v2", link = "https://github.com/hajimehoshi/ebiten"},
    {name = "pepeunit_go_client", link = "https://github.com/w7a8n1y4a/pepeunit_go_client"}
]
version = "1.1.1"
license = "AGPL v3 License"
authors = [
    {name = "Ivan Serebrennikov", email = "admin@silberworks.com"}
]

[images]
example = "https://minio.pepemoss.com/public-data/gif/hotkey_bublik.gif"

[env_description]
RADIUS_INNER = "Внутренний радиус первого бублика в пикселях"
THICK_SEGMENT = "Толщина сегментов бубликов в пикселях"
HOTKEY_MAIN = "Глобальный хоткей запуска интерфейса (например: `CTRL+SHIFT+P`). Если указать `null` — хоткей не регистрируется"

[topic_assignment]
"output_units_nodes/pepeunit" = "Предназначен для управления `Input` `UnitNode` других `Unit`, для корректной работы нужно добавить его через `Related Output`. Данные не публикуются в данный топик, а только в связи этого топика"

[work_algorithm]
steps = [
  "Чтобы приложение увидело `Unit` на первом слое бублика, нужно соеденить `output_units_nodes/pepeunit` с `Input` другого `Unit` в интерфейсах `Pepeunit`",
  "После запуска открыть интерфейс можно нажав кнопку `Меню` в `system tray` или через хоткей указанный в переменной `HOTKEY_MAIN`",
  "На первом слое бублика каждый сегмент - это отдельный `Unit`",
  "На втором слое бублика каждый сегмент - это отдельный `Input` `UnitNode` уже выбранного `Unit`",
  "На третьем слое бублика каждый сегмент - это сохранённые команды для отправки в выбранный `Input` `UnitNode`",
  "Возможные действия с сегментами подписаны под бубликами",
  "Команды создаваемые на третьем слое бублика хранятся на стороне `Pepeunit` через хранилище состояний в шифрованом виде",
  "В логах на экране отображаются последние `8` записей из `log.json`"
]

[installation]
steps = [
  "Скачайте бинарный файл последней версии из [releases](https://git.pepemoss.com/pepe/pepeunit/units/go/hotkey_donut/-/releases)",
  "Создайте `Unit` в `Pepeunit`",
  "Установите переменные окружения в `Pepeunit`",
  "Скачайте архив с `env.json` и `schema.json` из `Pepeunit`",
  "Запустите бинарный файл"
]
