[general]
name = "Donut controlling UnitNodes"
description = "Позволяет подготавливать и отправлять сообщения в `Input` `UnitNodes` других `Unit`"
language = "Golang"
hardware = ["Any-PC"]
firmware = ["Linux-X11"]
stack = [
    {name = "ebiten-v2", link = "https://github.com/hajimehoshi/ebiten"},
    {name = "pepeunit_go_client", link = "https://github.com/w7a8n1y4a/pepeunit_go_client"},
    {name = "systray", link = "https://github.com/getlantern/systray"},
    {name = "clipboard", link = "https://github.com/atotto/clipboard"},
    {name = "imaging", link = "https://github.com/disintegration/imaging"},
    {name = "screenshot", link = "https://github.com/kbinani/screenshot"}
]
version = "1.0.0"
license = "AGPL v3 License"
authors = [
    {name = "Ivan Serebrennikov", email = "admin@silberworks.com"}
]

[env_description]
RADIUS_INNER = "Внутренний радиус первого бублика в пикселях"
THICK_SEGMENT = "Ширина бубликов в пикселях"
HOTKEY_MAIN = "Глобальный хоткей запуска интерфейса (например: `CTRL+SHIFT+P`). Если указать `null` — хоткей не регистрируется."

[topic_assignment]
"output_units_nodes/pepeunit" = "Предназначен для управления `Input` `UnitNode` других `Unit`, для корректной работы нужно добавить его через `Related Output`. Данные не публикуются в данный топик, а только в связи этого топика"

[work_algorithm]
steps = [
  "Чтобы приложение увидело `Unit` на первом слое бублика, нужно соеденить `output_units_nodes/pepeunit` с `Input` другого `Unit` в интерфейсах `Pepeunit`",
  "После запуска открыть интерфейс можно нажав кнопку `Меню` в `system tray` или через хоткей в переменной `HOTKEY_MAIN`",
  "На первом слое бублика каждый сегмент - это отдельный `Unit`",
  "На втором слое бублика каждый сегмент - это отдельный `Input` уже выбранного `Unit`",
  "На третьем слое бублика каждый сегмент - это сохранённые опции для отправки в выбранный `Input` топик `Unit`",
  "При нажатии на `ЛКМ` отображается следующий слой",
  "При нажатии на `ПКМ` отображается предидущий слой",
  "На третьем слое - при нажатии на `ЛКМ` по `Сreate New Option` будет предложено сначала ввести название опции, после нажатия `Enter` будет предложено ввести данные, которые будут отправлены. Оба поля ввода поддерживают `ctrl-v`",
  "На третьем слое - при нажатии на `ЛКМ` по другим сегментам, будут отправляться `MQTT` сообщения в выбранный `Input` топик `Unit`",
  "На третьем слое - при нажатии горячей клавиши `Delete` опция будет удалена",
  "Опции создаваемые через `Сreate New Option` хранятся на стороне `Pepeunit` через хранилище состояний"
]

[installation]
steps = [
  "Скачайте бинарный файл последней версии из [releases](https://git.pepemoss.com/pepe/pepeunit/units/go/hotkey_donut/-/releases)",
  "Создайте `Unit` в `Pepeunit`",
  "Установите переменные окружения в `Pepeunit`",
  "Скачайте архив с `env.json` и `schema.json` из `Pepeunit`",
  "Запустите бинарный файл"
]
